[build]
command = "npx pnpm install --frozen-lockfile && npx pnpm run build"
publish = "public"

[build.environment]
NPM_FLAGS = "--version" # prevent Netlify npm install

[dev]
command = "remix watch"
port = 3000

[[headers]]
for = "/build/*"

[headers.values]
"Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
