name = "remix-cloudflare-workers"
workers_dev = true
main = "./build/index.js"
compatibility_date = "2022-05-16"
account_id = "8ca5e9eea2204ecfd6772e384fb13b68"

[site]
bucket = "./public"


[build]
command = "npm run build"
