name: CI
on: 
  push:
    branches:
      - main
      - dev
  pull_request: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.1.0
      with:
        version: 7.0.0-rc.3
    - name: Install modules
      run: pnpm i
    - name: Run typescript type check
      run: pnpm run typecheck
    - name: Run ESLint
      run: pnpm run lint
