name: Deploy
on: 
  push:
    branches:
      - main
      - dev
  pull_request: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm ci
    - name: Run typescript type check
      run: npm run typecheck
    - name: Run ESLint
      run: npm run lint
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Install modules
        run: npm ci
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          secrets: |
            HASURA_ENDPOINT
            HASURA_TOKEN
        env:
          HASURA_ENDPOINT: ${{ secrets.HASURA_ENDPOINT }}
          HASURA_TOKEN: ${{ secrets.HASURA_TOKEN }}
